export const GET_ALL_FLIGHT_DETAILS_REQUEST = "GET_ALL_FLIGHT_DETAILS_REQUEST"

export const GET_ALL_FLIGHT_DETAILS_SUCCESS = "GET_ALL_FLIGHT_DETAILS_SUCCESS"

export const GET_ALL_FLIGHT_DETAILS_FAILS = "GET_ALL_FLIGHT_DETAILS_FAILS"
